### ISSUE TITLE
Add Release Link for `check`

### ISSUE THREAD

**Issue by ebebbington** [drashland/dmm#1]
## Summary

When checking, and if a dependency can be updated, add a link to stdout to the release notes.

Should be relatively easy as the logic that gets the latest version uses a URL to their releases, for example: `github.com/.../releases/latest` - it should just be a matter of saving this url and adding it to the module object as a `releaseURL` property or something. Then log these out. 

It might require some formatting to make the output look clean, for example:

Now:
```
...
fs can be updated from [version] to [version]
...
```

Adding formatting:
```
...

- fs
  Can be updated from [version] to [version]
  [release link]
...
```

## Acceptance Criteria

- [ ] Add a release link to each module that should be displayed on `check`
- [ ] Update/fix tests
- [ ] Update README (if needed)

**Pseudo-code for Implementation**

```typescript
// src/interfaces/module.ts

// Add: latestReleaseLink?: string|boolean
```
```typescript
// src/services/module_service.ts

// Inside the for loop for `constructModulesDataFromDeps`:
const latestReleaseLink = importedVersion !== latestRelease ?
    gitHubUrl + "/releases/latest"
    :
    false

...

modules.push({
    ...
    latestReleaseLink
})
```
```typescript
// src/commands/check.ts
modules.forEach((module) => {
    if (module.importedVersion !== module.latestRelease) {
      depsCanBeUpdated = true;
      listOfModuleNamesToBeUpdated.push(module.name);
      console.info(
        colours.yellow(
+         "- " + module.name + "\n" +
+        "    Can be updated from " + module.importedVersion + " to " + module.latestRelease + "\n" +
+        "    " + module.latestReleaseLink
        ),
      );
    }
  });
```

## Taking on this issue? Read this before you get started.

If you take on this issue and the acceptance criteria does not make sense, post comments on this issue with your questions. Also, you can always hop in the Discord channel at https://discord.gg/c5R3sYuR to get help quickly.

Please read the [Contributing Guidelines](https://github.com/drashland/.github/blob/master/CONTRIBUTING.md) before starting this issue.

**Comment by crookse** [comment]
I like this convenience

**Comment by ebebbington** [comment]
closing because this wil be removed in #117
