### ISSUE TITLE
PermissionDenied: Requires read access to "."

### ISSUE THREAD

**Issue by kinghat** [drashland/dmm#129]
## Summary

the docs say to run with `--allow-read='deps.ts'` but i get the following permission error. if i run with `--allow-read='.'`, like in the previous version, its fine.

> $ deno run --allow-net='cdn.deno.land,api.deno.land,x.nest.land,raw.githubusercontent.com,github.com,api.github.com' --allow-read='deps.ts' --allow-write='deps.ts' https://deno.land/x/dmm/mod.ts update
[INFO] Reading deps.ts to gather your dependencies...
error: Uncaught (in promise) PermissionDenied: Requires read access to ".", run again with the --allow-read flag
    const usersWorkingDir: string = Deno.realPathSync(".");
                                         ^
    at Object.opSync (deno:core/01_core.js:149:12)
    at Object.realPathSync (deno:runtime/js/30_fs.js:137:17)
    at Function.constructModulesDataFromDeps (https://deno.land/x/dmm@v2.0.0/src/services/module_service.ts:61:42)
    at UpdateSubcommand.handle (https://deno.land/x/dmm@v2.0.0/src/commands/update.ts:17:41)
    at UpdateSubcommand.run (https://deno.land/x/line@v1.0.0/src/subcommand.ts:82:16)
    at Dmm.#runSubcommand (https://deno.land/x/line@v1.0.0/src/main_command.ts:228:32)
    at Dmm.run (https://deno.land/x/line@v1.0.0/src/main_command.ts:65:30)
    at CLI.run (https://deno.land/x/line@v1.0.0/src/cli.ts:86:29)
    at https://deno.land/x/dmm@v2.0.0/mod.ts:20:5

**Comment by crookse** [comment]
thanks for bring this up! ill try to look into this today @kinghat

**Comment by crookse** [comment]
@kinghat i looked into this issue and a current working solution is:

```
deno run \
   --allow-net='cdn.deno.land,api.deno.land,x.nest.land,raw.githubusercontent.com,github.com,api.github.com' \

   --allow-read='.' \    <----- this is the change right here

   --allow-write='deps.ts' \
   https://deno.land/x/dmm/mod.ts \
   update
```

not sure when the change happened to `Deno.realPathSync()`, but yea our docs aren't saying the correct thing anymore. Seems as though you now only need to do:

```
--allow-read="."
```

as opposed to

```
--allow-read="deps.ts"
```

using `--allow-read="."` is sufficient enough for dmm to read your current working directory and all nested files/directories

**Comment by crookse** [comment]
i know you closed this, but i'll continue to see if we can be backwards compatible. not really confident that we will be because deno std is still v0, but i'll give it a shot

**Comment by kinghat** [comment]
> i know you closed this, but i'll continue to see if we can be backwards compatible. not really confident that we will be because deno std is still v0, but i'll give it a shot

ill reopen and let you decide when is best to close.

**Comment by ebebbington** [comment]
Ideally we could strip away the realPathSync call, and replac eit with something else, so the user doesnt need to give read permission - dmm **should** only read and write to **a single file**, so it should only have access to that one file
