### ISSUE TITLE
bug: versions with `-rc34` does not trim the `-rc34` before updating the deps.ts file.

### ISSUE THREAD

**Issue by xCykrix** [drashland/dmm#149]
## Summary

Versions with a release candidate or non-traditional versioning is not correctly replaced.

## Steps To Reproduce The Bug

1. Create a deps.ts with the following:
```ts
export { createBot } from 'https://deno.land/x/discordeno@13.0.0-rc34/mod.ts';
```
2. Run dmm on the file.
3. Observed: `13.0.0-rc34` becomes `13.0.0-rc36-rc34`

## Expected Behavior

The entire version string should be found, not just the 13.0.0.

## Suggested Solution(s)

Correction to the version matching detection.

## Screenshots

N/A

## Additional Context

[INFO] Reading deps.ts to gather your dependencies...
[INFO] Checking if your modules can be updated...
[INFO] discordeno was updated from 13.0.0 to 13.0.0-rc36

**Comment by ebebbington** [comment]
@xCykrix thanks, we'll fix this soon :)

**Comment by xCykrix** [comment]
Sounds good. I just stumbled along Drash and looking forward to experimenting with some of the modules. :)

**Comment by ebebbington** [comment]
@xCykrix checkout v2.0.2, this should have been fixed :) discordeno has been added to the tests so we're 100% it will work with those types of version strings

**Comment by xCykrix** [comment]
Thanks!
