### ISSUE TITLE
support for unpkg.com CDN

### ISSUE THREAD

**Issue by mknj** [drashland/dmm#155]
Please support unpkg.com as CDN

```js
import Table from "https://unpkg.com/table-layout@2.0.0/dist/index.mjs"
```

To get the latest version of a package, simply remove the @version from the url and parse the location header.

```
❯ curl https://unpkg.com/table-layout/dist/index.mjs
Found. Redirecting to /table-layout@3.0.0/dist/index.mjs⏎        
```

**Comment by ebebbington** [comment]
@mknj this has been added and released, use v2.1.0 and it should update :)
