### ISSUE TITLE
Add Warning If Using Master Branch

### ISSUE THREAD

**Issue by ebebbington** [drashland/dmm#2]
* Update readme to mention this module will only read lines with versions

* Add a warning message for a dependency if its imported using the master branch
    * Would probably be present on `check` and `update`

## Taking on this issue? Read this before you get started.

If you take on this issue and the acceptance criteria does not make sense, post comments on this issue with your questions. Also, you can always hop in the Discord channel at https://discord.gg/c5R3sYuR to get help quickly.

Please read the [Contributing Guidelines](https://github.com/drashland/.github/blob/master/CONTRIBUTING.md) before starting this issue.

**Comment by crookse** [comment]
I agree with this. Deno does something similar. When it downloads modules and a module isn't versioned, it says something like, "Implicitly using master branch."

**Comment by ebebbington** [comment]
FYI for when development starts, the logic for this could be inside `module_service.ts`, on reading each line, if a line is not versioned, add a warning message, eg:
```
... for each dep:
    if dep.indexOf("@") === -1
        console.warn(colours.yellow("You are implicitly using the master branch of " + name)
```

**Comment by ebebbington** [comment]
tbh just gonna close this, would be cool but the user would already know whenever they run their code, deno will give a warning, i dont think we need to give the user another set of warnings

@crookse feel free to reopen if you would personally like this implemented though :)
