### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by ebebbington** [drashland/dmm#3]
The tests for the `update` command are all commented out as I haven't yet had the time to think about how we would go about testing it, as I assume we would need to test that a `deps.ts` has been modified to upgrade versions, but we'd want this file to be defaulted to it's original state for the other update tests

* Finish the tests inside `/tests/update_test.ts`

**Comment by ebebbington** [comment]
I believe it can be done like so:

* Have an `original_deps.ts` and a `deps.ts`, both with the same content.
* Run the update tests and when the `deps.ts` gets updated, replace it with the original (at the end of the test)

**Comment by crookse** [comment]
Sounds like a solid solution
