### ISSUE TITLE
Support Nest.Land as a Registry

### ISSUE THREAD

**Issue by ebebbington** [drashland/dmm#31]
## Summary

What: Right now, dmm only supports imports from Deno.land. It would be good to support usage from nest.land too, as not doing so puts a limitation on users using dmm. Although Nest have their own CLI, I still think it would be good should people wish to use Nest imports **and** dmm

Why: Lifts a limitation for users, to not restrict imports to only one registry (that Deno wanted to avoid eg npm)

## Acceptance Criteria

- [ ] Add x.nest.land to the supported registries. Atm this is just if the line contains Deno.land, but might be good to hold a const for supported registries and add this to documentation

## Example Pseudo Code (for implementation)

```typescript
Class ModuleService {
    protected supported_registries = [
        deno.land
        X.nest.land
    ]

    ...

    const isSupported = this.supported_registries.filter(r => line.indexOf(r) !== -1).length > 0
```

**Comment by ebebbington** [comment]
Thought?

**Comment by Guergeiro** [comment]
I agree with it!

**Comment by crookse** [comment]
Agreed

**Comment by ebebbington** [comment]
Now nest.land supports the std registry (mirror), this needs to be taken into account, to account for. x.nest.land imports on 3rd party or std (as i believe they are written differently). Might be worth having a `nest_service.ts` to abstract this kind of logic (and possible extend `module_service`?)

**Comment by TheWizardBear** [comment]
Can I take on this issue?

**Comment by ebebbington** [comment]
Feel free :)
