### ISSUE TITLE
Specify Path to Deps File

### ISSUE THREAD

**Issue by ebebbington** [drashland/dmm#36]
## Summary

What:

From the CLI,  allow a user to specify a path to a dependency file. This should (and could) be used in conjunction with the following commands: update, check.

Along with this, allow the user to pass in a `--dir` flag. If the user passes this in, then dmm should read every file within that directory (shouldn't check if the filenames have `deps` in it). 

Why:

Some people of Deno (including ourselves) are taking the approach to having more than 1 deps file, eg `test_deps.ts` in a different folder - this would support that

## Acceptance Criteria

- [ ] A `--file=some_file.ts` flag can be passed, and only that file will be checked
- [ ] A `--dir=some_dir` flag can be passed, and each file within that dir will be checked
    - [ ] If there is another dir inside that dir, then the logic should call itself to check that nested directory
- [ ] Above flags cannot be used together
- [ ] Update README
- [ ] Update `src/options/help.ts`
- [ ] Tests covering this
- [ ] `src/options/help.ts` updated to reflect changes

## Example Pseudo Code (for implementation)

* Default to `deps.ts`when that option was passed

* If it was, ensure the file exists

    * If it doesnt, send error

* Read. the file as normal

* Example usage would be:  `dmm. update --file=tests/deps.ts`

```typescript
function updateDir(dirName) {
  const everything[] = openAllFilesDirectory(dirName);
  for (const file of everything) {
    if (file.isNotTypeScript() == true) {
      continue;
    }
    if (file.isDirectory() == true) {
      updateDir(file);
      continue;
    }
    functionToUpdateFile(file);
  }
}
```

## Taking on this issue? Read this before you get started.

If you take on this issue and the acceptance criteria does not make sense, post comments on this issue with your questions. Also, you can always hop in the Discord channel at https://discord.gg/c5R3sYuR to get help quickly.

Please read the [Contributing Guidelines](https://github.com/drashland/.github/blob/master/CONTRIBUTING.md) before starting this issue.

**Comment by kinghat** [comment]
what if you made dmm crawl to the nearest deps file by default? you could also allow the deps file/dir to be passed explicitly :thinking:

**Comment by ebebbington** [comment]
> what if you made dmm crawl to the nearest deps file by default? you could also allow the deps file/dir to be passed explicitly 🤔

“The nearest” deps file is just too much magic, how many parent directories should we check, how many child directories should we traverse? I just think it can get ugly pretty path and if a user has their deps file someplace obscure, they can specify that

also, this issue is to support passing the deps file explicitly :) and if they it passing the directory, they may as well pass the file (because some people have different names for their deps files, so to us, their deps file could be anything)

**Comment by kinghat** [comment]
> “The nearest” deps file is just too much magic, how many parent directories should we check, how many child directories should we traverse? I just think it can get ugly pretty path and if a user has their deps file someplace obscure, they can specify that

i just figured crawling infinitely wasnt an issue since vscode does it when looking for settings files and git repos :man_shrugging: in reality its never that far away.

> also, this issue is to support passing the deps file explicitly :) and if they it passing the directory, they may as well pass the file (because some people have different names for their deps files, so to us, their deps file could be anything)

this makes sense, thanks :ok_hand:
