### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by crookse** [drashland/dmm#40]
**Describe the bug**

The CI showed that the tests were failing due to dependencies having been upgraded. For example, Drash was upgraded to v1.1.0, but the tests were expecting a different version and not the latest version.

**To Reproduce**

```
deno test --allow-net --allow-env --allow-run
```

Also, see: https://github.com/drashland/dmm/runs/886656005?check_suite_focus=true

**Expected behavior**

Tests should pass.

**Comment by ebebbington** [comment]
Easy fix, should only take 10 minutes max, it's just a matter of updating the versions throughout the tests
