### ISSUE TITLE
error: Invalid executable name

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [drashland/dmm#61]
**Describe the bug**
When trying the installation route, it fails on
```
Check https://deno.land/x/dmm@v1.1.5/mod.ts
error: Invalid executable name: dmm@v1.1.5
```

**To Reproduce**
Using the `deno install --allow-net --allow-read --allow-write https://deno.land/x/dmm@v1.1.5/mod.ts` command.

**Expected behavior**
Successful installtion.

**Screenshots**
![image](https://user-images.githubusercontent.com/36411819/91420566-2f33a780-e855-11ea-9cbd-192f3710e45d.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux 20.1
- Deno: 1.3.1

Please let me know if you need additional information.

**Comment by ebebbington** [comment]
Thanks for raising this @BunnyTheLifeguard , we’ll try look into it later 👍

**Comment by BunnyTheLifeguard** [comment]
After solving issues with other tools (bash: command not found errors) using deno install, and using `echo 'export PATH="$HOME/.deno/bin:$PATH"' >> ~/.bashrc` to solve them to be able to successfully use installed command, the error changed.

Now I get this one during the installation attempt:
```
Download https://deno.land/x/dmm@v1.1.5/src/services/module_service.ts
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
      sorted: true,
      ~~~~~~~~~~~~
    at https://deno.land/std@0.65.0/testing/asserts.ts:26:7
```

![image](https://user-images.githubusercontent.com/36411819/91423694-2644d500-e859-11ea-8d9b-bad657da5b38.png)

**Comment by ebebbington** [comment]
@BunnyTheLifeguard what Deno version are you using now the error has changed?

**Comment by BunnyTheLifeguard** [comment]
> @BunnyTheLifeguard what Deno version are you using now the error has changed?

It's still v1.3.1, didn't change it.

**Comment by ebebbington** [comment]
Ok both errors are odd... the weird thing with the second one (sorted: true error) is that it's an error for using std 0.61 or greater but your deno version is less than. 1.2.0 :S (see [here](https://github.com/denoland/deno/issues/6788))

I've seen that error before, but not `invalid executable name: ...` - i do actually see the first error when i try install through deno.land, but if i install through the `mod.ts` everything works fine (i'm on deno v1.3.1 as well)

Try run with the `--name` flag: `deno install -f --allow-net --allow-read --allow-write --name dmm https://deno.land/x/dmm@v1.1.5/mod.ts`

I wonder if the `invalid executable name` is a bug with deno

**Comment by BunnyTheLifeguard** [comment]
@ebebbington Thanks, tried your command, but it throws the same error :/
Really trying to like Deno, but things like this make it pretty hard to 😅

**Comment by ebebbington** [comment]
Can you try run the following steps:

1. Upgrade again: `deno upgrade`, then try install again (with and without using the `--name dmm` flag)
2. If it still doesn't work, then try clear the cache: `rm -rf $(deno info | grep "DENO_DIR location" | awk '{print substr($0,index($0, "\""))}')` and try install again

I've made an issue with Deno as I *believe* it's deno-related, so feel free to chime in as you're still unable to resolve the problem: https://github.com/denoland/deno/issues/7221

**Comment by BunnyTheLifeguard** [comment]
@ebebbington Thanks for the support 🙂 Tried everything you've mentioned, unfortunately it did not help so far.

**Comment by BunnyTheLifeguard** [comment]
@ebebbington Like you probably already read the issue for me was that my Deno in the project folder was still on 1.0.0. 🤪
After upgrading this one installation with name flag worked. Initial issue still remains, like you confirmed. Should we close this issue here?

**Comment by ebebbington** [comment]
Yeah ;) Good to hear :) May as well close this issue then
