### ISSUE TITLE
Question: Do you plan to publish this module also for https://nest.land/ ?

### ISSUE THREAD

**Issue by michael-spengler** [drashland/dmm#63]
https://nest.land/

**Comment by Guergeiro** [comment]
Hello @michael-spengler. We do plan on doing this. I'm guilty of this because I thought that we already had all of the major repositories in Drashland and this one slipped between our fingers.

**Comment by ebebbington** [comment]
Hey, dmm is already on best if I’m not mistaken? https://nest.land/package/dmm

**Comment by Guergeiro** [comment]
Okay, then we should add the best badge to the repo. Maybe even in all of Drashland repos.

**Comment by ebebbington** [comment]
Yeah I think it might be a good shout to have something visible to say it’s on nest - though I feel the badge is quite long winded (eg it takes up a lot of space for one badge) but maybe I’m just picky af

Though I feel if we have a badge, then it we may as well have a badge for Deno too?

Another thing actually is what if more registries are created - then we’d have a badge for each one

**Comment by michael-spengler** [comment]
sorry - did not find it when I first looked for it

**Comment by michael-spengler** [comment]
will add the badge - PR coming in 5 min

**Comment by michael-spengler** [comment]
done - in case you are not already in: the link to the arweave discord server might be interesting to you: https://discord.gg/xJhCUf 

... closing this issue ...
