### ISSUE TITLE
dmm downgrade [module] [version]

### ISSUE THREAD

**Issue by crookse** [drashland/dmm#87]
## Summary

What:

Have a `downgrade` subcommand that downgrades modules to a specific version or the previous version.

Why:

If someone updates their deps and realizes later that their deps don't work with their project and they want to downgrade their deps, they need to do it manually. `dmm downgrade` would do it for them.

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests

**Comment by ebebbington** [comment]
@crookse is this something you'd still want?

**Comment by crookse** [comment]
idk. seems like a moot point. downgrading deps doesn't take much effort to do and it would probably be best if the user downgraded manually. i say that because if they downgrade via dmm downgrade, then realize they downgrade wrong package, they need to update the package. seems like changing the version numbers manually instead of doing dmm commands in this scenario would be more intuitive and put the user in a better spot when debugging incompatible versions

gonna close this
