### ISSUE TITLE
Update regex to match true semver tags

### ISSUE THREAD

**Issue by crookse** [drashland/dmm#90]
## Summary

What:

Currently, our regex matches v1.2.3, 1.2.3, 1.2.3.4.5.6 (and so on), but semver tags could be v1.2.3-rc1. We don't support that and we should.

Why:

We don't know what module versions will be released -- whether they're following semver or not, but if they are following semver, then it's possible that a module's version could be v1.2.3-alpha; and we don't support that yet.

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Match semver tags (see semver.org for possible semver tags)
- [ ] Write unit tests

**Comment by ebebbington** [comment]
Wait we actually do now xD Idk when we added it..

https://github.com/drashland/dmm/commit/fd8bf9d79baf98580fa6c6e17961f7d446d147e4

**Comment by crookse** [comment]
LMFAO
